INCLUDE memory-fe310.x
MEMORY
{
    /* The bootloader actually fits into 1K with proper optimizations */
    FLASH : ORIGIN = 0x20000000, LENGTH = 4K
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
